# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os, sys

# đường dẫn tới folder platforms vừa copy 
THIS_DIR = os.path.abspath(os.path.dirname(__file__))
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = os.path.join(os.getcwd(), 'platforms')
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(597, 395)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 40, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_plain = QtWidgets.QLabel(Dialog)
        self.label_plain.setGeometry(QtCore.QRect(40, 120, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_plain.setFont(font)
        self.label_plain.setObjectName("label_plain")
        self.txt_plain_text = QtWidgets.QTextEdit(Dialog)
        self.txt_plain_text.setGeometry(QtCore.QRect(140, 110, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_plain_text.setFont(font)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.label_key = QtWidgets.QLabel(Dialog)
        self.label_key.setGeometry(QtCore.QRect(40, 190, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_key.setFont(font)
        self.label_key.setObjectName("label_key")
        self.txt_key = QtWidgets.QTextEdit(Dialog)
        self.txt_key.setGeometry(QtCore.QRect(140, 180, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_key.setFont(font)
        self.txt_key.setObjectName("txt_key")
        self.label_cipher = QtWidgets.QLabel(Dialog)
        self.label_cipher.setGeometry(QtCore.QRect(40, 250, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_cipher.setFont(font)
        self.label_cipher.setObjectName("label_cipher")
        self.txt_cipher_text = QtWidgets.QTextEdit(Dialog)
        self.txt_cipher_text.setGeometry(QtCore.QRect(140, 240, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_cipher_text.setFont(font)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.btn_encrypt = QtWidgets.QPushButton(Dialog)
        self.btn_encrypt.setGeometry(QtCore.QRect(380, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_encrypt.setFont(font)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(Dialog)
        self.btn_decrypt.setGeometry(QtCore.QRect(490, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_decrypt.setFont(font)
        self.btn_decrypt.setObjectName("btn_decrypt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Caesar Cipher"))
        self.label.setText(_translate("Dialog", "CAESAR CIPHER"))
        self.label_plain.setText(_translate("Dialog", "Plain text"))
        self.label_key.setText(_translate("Dialog", "Key"))
        self.label_cipher.setText(_translate("Dialog", "Cipher text"))
        self.btn_encrypt.setText(_translate("Dialog", "Encrypt"))
        self.btn_decrypt.setText(_translate("Dialog", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
