# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ECCDialog(object):
    def setupUi(self, ECCDialog):
        ECCDialog.setObjectName("ECCDialog")
        ECCDialog.resize(800, 360)
        self.lblTitle = QtWidgets.QLabel(ECCDialog)
        self.lblTitle.setGeometry(QtCore.QRect(300, 10, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.btn_gen_keys = QtWidgets.QPushButton(ECCDialog)
        self.btn_gen_keys.setGeometry(QtCore.QRect(660, 20, 120, 30))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.lblInfo = QtWidgets.QLabel(ECCDialog)
        self.lblInfo.setGeometry(QtCore.QRect(80, 70, 100, 20))
        self.lblInfo.setObjectName("lblInfo")
        self.txt_info = QtWidgets.QTextEdit(ECCDialog)
        self.txt_info.setGeometry(QtCore.QRect(80, 95, 650, 80))
        self.txt_info.setObjectName("txt_info")
        self.lblSign = QtWidgets.QLabel(ECCDialog)
        self.lblSign.setGeometry(QtCore.QRect(80, 190, 100, 20))
        self.lblSign.setObjectName("lblSign")
        self.txt_sign = QtWidgets.QTextEdit(ECCDialog)
        self.txt_sign.setGeometry(QtCore.QRect(80, 215, 650, 50))
        self.txt_sign.setObjectName("txt_sign")
        self.btn_sign = QtWidgets.QPushButton(ECCDialog)
        self.btn_sign.setGeometry(QtCore.QRect(80, 280, 80, 50))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(ECCDialog)
        self.btn_verify.setGeometry(QtCore.QRect(180, 280, 80, 50))
        self.btn_verify.setObjectName("btn_verify")

        self.retranslateUi(ECCDialog)
        QtCore.QMetaObject.connectSlotsByName(ECCDialog)

    def retranslateUi(self, ECCDialog):
        _translate = QtCore.QCoreApplication.translate
        ECCDialog.setWindowTitle(_translate("ECCDialog", "ECC Cipher"))
        self.lblTitle.setText(_translate("ECCDialog", "ECC CIPHER"))
        self.btn_gen_keys.setText(_translate("ECCDialog", "Generate Keys"))
        self.lblInfo.setText(_translate("ECCDialog", "Information:"))
        self.lblSign.setText(_translate("ECCDialog", "Signature:"))
        self.btn_sign.setText(_translate("ECCDialog", "Sign"))
        self.btn_verify.setText(_translate("ECCDialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ECCDialog = QtWidgets.QDialog()
    ui = Ui_ECCDialog()
    ui.setupUi(ECCDialog)
    ECCDialog.show()
    sys.exit(app.exec_())
