# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING! All manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
# chính xác trỏ đến thư mục platforms ở ngang cấp với ui
THIS_DIR = os.path.abspath(os.path.dirname(__file__))
PLUGINS  = os.path.abspath(os.path.join(THIS_DIR, '..', 'platforms'))
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = PLUGINS

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog  


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 360)
        self.lblTitle = QtWidgets.QLabel(Dialog)
        self.lblTitle.setGeometry(QtCore.QRect(300, 10, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.btn_gen_keys = QtWidgets.QPushButton(Dialog)
        self.btn_gen_keys.setGeometry(QtCore.QRect(660, 20, 120, 30))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.lblPlain = QtWidgets.QLabel(Dialog)
        self.lblPlain.setGeometry(QtCore.QRect(20, 70, 100, 20))
        self.lblPlain.setObjectName("lblPlain")
        self.txt_plain_text = QtWidgets.QTextEdit(Dialog)
        self.txt_plain_text.setGeometry(QtCore.QRect(20, 95, 360, 80))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.lblCipher = QtWidgets.QLabel(Dialog)
        self.lblCipher.setGeometry(QtCore.QRect(20, 190, 100, 20))
        self.lblCipher.setObjectName("lblCipher")
        self.txt_cipher_text = QtWidgets.QTextEdit(Dialog)
        self.txt_cipher_text.setGeometry(QtCore.QRect(20, 215, 360, 50))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.btn_encrypt = QtWidgets.QPushButton(Dialog)
        self.btn_encrypt.setGeometry(QtCore.QRect(120, 280, 80, 30))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(Dialog)
        self.btn_decrypt.setGeometry(QtCore.QRect(260, 280, 80, 30))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.lblInfo = QtWidgets.QLabel(Dialog)
        self.lblInfo.setGeometry(QtCore.QRect(420, 70, 120, 20))
        self.lblInfo.setObjectName("lblInfo")
        self.txt_info = QtWidgets.QTextEdit(Dialog)
        self.txt_info.setGeometry(QtCore.QRect(420, 95, 360, 80))
        self.txt_info.setObjectName("txt_info")
        self.lblSign = QtWidgets.QLabel(Dialog)
        self.lblSign.setGeometry(QtCore.QRect(420, 190, 120, 20))
        self.lblSign.setObjectName("lblSign")
        self.txt_sign = QtWidgets.QTextEdit(Dialog)
        self.txt_sign.setGeometry(QtCore.QRect(420, 215, 360, 50))
        self.txt_sign.setObjectName("txt_sign")
        self.btn_sign = QtWidgets.QPushButton(Dialog)
        self.btn_sign.setGeometry(QtCore.QRect(480, 280, 80, 30))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(Dialog)
        self.btn_verify.setGeometry(QtCore.QRect(620, 280, 80, 30))
        self.btn_verify.setObjectName("btn_verify")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RSA Cipher"))
        self.lblTitle.setText(_translate("Dialog", "RSA CIPHER"))
        self.btn_gen_keys.setText(_translate("Dialog", "Generate Keys"))
        self.lblPlain.setText(_translate("Dialog", "Plain Text:"))
        self.lblCipher.setText(_translate("Dialog", "Cipher Text:"))
        self.btn_encrypt.setText(_translate("Dialog", "Encrypt"))
        self.btn_decrypt.setText(_translate("Dialog", "Decrypt"))
        self.lblInfo.setText(_translate("Dialog", "Information:"))
        self.lblSign.setText(_translate("Dialog", "Signature:"))
        self.btn_sign.setText(_translate("Dialog", "Sign"))
        self.btn_verify.setText(_translate("Dialog", "Verify"))
if __name__ == "__main__":
    app    = QApplication(sys.argv)
    dialog = QDialog()
    ui     = Ui_Dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())